# Generated by Django 2.1.9 on 2020-04-15 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageType',
        ),
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.Page')),
            ],
            options={
                'verbose_name': 'Тип страницы',
                'verbose_name_plural': 'Типы страниц',
            },
            bases=('cms.page',),
        ),
        migrations.AlterField(
            model_name='PagePermission',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='Page',
            name='publisher_public',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_draft', to='cms.Page'),
        ),
        migrations.AlterField(
            model_name='Title',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_set', to='cms.Page', verbose_name='page'),
        ),
    ]
